[am]
name = "AM"
desc = "Ante meridiem"
see = ['PM']

[ar.country]
name = "AR"
desc = "Argentina"

[au.country]
name = "AU"
desc = "Australia"

[apec]
name = "APEC"
desc = "Asia-Pacific Economic Cooperation"
