[cnn]
disp = "CNN"
desc = "The Cable News Network"
full = "A multinational news-based pay television channel headquartered in Atlanta, United States. "

[cmu]
disp = "CMU"
desc = "Carnegie Mellon University"

[cn.country]
disp = "cn"
desc = "China"

[ca.country]
disp = "ca"
desc = "Canada"

[ca.America]
disp = "CA"
desc = "California in America"
