[cnn]
disp = "CNN"
desc = "The Cable News Network"
full = "A multinational news-based pay television channel headquartered in Atlanta, United States. "

[cmu]
disp = "CMU"
desc = "Carnegie Mellon University"
