[cnn]
name = "CNN"
desc = "The Cable News Network"
more = "A multinational news-based pay television channel headquartered in Atlanta, United States. "

[cmu]
name = "CMU"
desc = "Carnegie Mellon University"

[cn.country]
name = "cn"
desc = "China"

[ca.country]
name = "ca"
desc = "Canada"

[ca.America]
name = "CA"
desc = "California in America"
