[es.country]
disp = "es"
desc = "Spain"

[eg]
same = "'e.g.'"

["eg."]
same = "'e.g.'"

["e.g."]
disp = "e.g."
desc = "exempli gratia"
full = "The phrase is Latin for 'for example'"
see = ['i.e.']

["etc."]
disp = "etc."
desc = "Et cetera"
full = "'and the rest' in Latin"
