[es.country]
name = "es"
desc = "Spain"

[eg]
same = "'eg.'"

["eg."]
same = "'e.g.'"

["e.g."]
name = "e.g."
desc = "exempli gratia"
full = "The phrase is Latin for 'for example'"
see = ['i.e.']

["etc."]
name = "etc."
desc = "Et cetera"
full = "'and the rest' in Latin"
