[es.country]
name = "es"
desc = "Spain"

[eg]
same = "'eg.'"

["eg."]
same = "'e.g.'"

["e.g."]
name = "e.g."
desc = "exempli gratia"
more = "The phrase is Latin for 'for example'"
see = ['i.e.']

[etc]
same = "'etc.'"

["etc."]
name = "etc."
desc = "Et cetera"
more = "'and the rest' in Latin"

[eq]
name = "EQ"
desc = "Emotional Intelligence Quotient"

[esi]
name = "ESI"
desc = "Essential Science Indicators"

[easa]
name = "EASA"
desc = "European Aviation Safety Agency"
