[fwiw]
name = "FWIW"
desc = "for what it’s worth"

[fr]
name = "fr"
desc = "France"

[faq]
name = "FAQ"
desc = "Frequently Asked Questions"

[fyi]
name = "FYI"
desc = "For your information"

[fbi]
name = "FBI"
desc = "Federal Bureau of Investigation"

[faa]
name = "FAA"
desc = "Federal Aviation Administration"
