[fwiw]
disp = "FWIW"
desc = "for what it’s worth"

[fr]
disp = "fr"
desc = "France"

[faq]
disp = "FAQ"
desc = "Frequently Asked Questions"

[fyi]
disp = "FYI"
desc = "For your information"

[fbi]
disp = "FBI"
desc = "Federal Bureau of Investigation"
