[ip]
name = "IP"
desc = "Intellectual Property"

[io.district]
name = "io"
desc = "British Indian Ocean Territory"

[ilstu]
name = "ILSTU"
desc = "Illinois State University"

[ime]
name = "IME"
desc = "In My Experience"

[imo]
name = "IMO"
desc = "In My Opinion"

[ie]
same = "'ie.'"

['ie.']
same = "'i.e.'"

["i.e."]
name = "i.e."
desc = "id est"
more = "Latin phrase for 'that is' (literally 'it is')"
see = ['e.g.']

[iirc]
name = "IIRC"
desc = "if I Recall Correctly"

[iiuc]
name = "IIUC"
desc = "If I Understand Correctly"

[iq]
name = "IQ"
desc = "Intelligence Quotient"
