[kfc]
name = "KFC"
desc = "Kentucky Fried Chicken"

[kcl]
name = "KCL"
desc = "King's College London"

[k12]
name = "K12"
desc = "from kindergarten to 12th grade"

[kol]
name = "KOL"
desc = "Key Opinion Leader"

[kth]
name = "KTH"
desc = "Kungliga tekniska högskolan"
more = "KTH Royal Institute of Technology in Sweden"
