[mit]
name = "MIT"
desc = "Massachusetts Institute of Technology"

[ma.America]
name = "MA"
desc = "Massachusetts in America"

[mvp]
name = "MVP"
desc = "Most Valuable Player"

[maa]
name = "MAA"
desc = "Mathematical Association of America"

[mbti]
name = "MBTI"
desc = "Myers-Briggs Type Indicator"

[mooc]
name = "MOOC"
desc = "Massive Open Online Courses"
