[nasa]
name = "NASA"
desc = "National Aeronautics and Space Administration"

[nsa]
name = "NSA"
desc = "National Security Agency"

["n.b."]
name = "n.b. or NB"
desc = "Nota bene"
more = "The phrase is Latin for 'note well'. In Modern English, it is used, particularly in legal papers, to draw the attention of the reader to a certain (side) aspect or detail of the subject being addressed. "
