[okr]
name = "OKR"
desc = "Objectives and Key Results"

[or.America]
name = "OR"
desc = "Oregon State in America"

[op]
name = "OP (Reddit)"
desc = "Original Poster"

[ot]
name = "OT"
desc = "Off Topic"
