[sms]
name = "SMS"
desc = "Short Message Service"

[sig]
name = "SIG"
desc = "Special Interest Group"

[sg]
name = "sg"
desc = "Singapore"

[sjtu]
name = "SJTU"
desc = "Shanghai Jiao Tong University"

[stem]
name = "STEM subjects"
desc = '''

  1. Science
  2. Technology
  3. Engineering
  4. Maths'''

[ssci]
name = "SSCI"
desc = "Social Sciences Citation Index"
see = ['SCI', 'EI']
