[sms]
disp = "SMS"
desc = "Short Message Service"

[sig]
disp = "SIG"
desc = "Special Interest Group"

[sg]
disp = "sg"
desc = "Singapore"

[sjtu]
disp = "SJTU"
desc = "Shanghai Jiao Tong University"
