[sms]
name = "SMS"
desc = "Short Message Service"

[sig]
name = "SIG"
desc = "Special Interest Group"

[sg]
name = "sg"
desc = "Singapore"

[sjtu]
name = "SJTU"
desc = "Shanghai Jiao Tong University"
