[toefl]
name = "TOEFL"
desc = "Test of English as a Foreign Language"

[tw.district]
name = "tw"
desc = "Taiwan"

[tldr]
name = "TL;DR"
desc = "Too long; Didn't read"

[ted]
name = "TED conference"
desc = "Technology, Entertainment, Design"
