[zh]
name = "zh"
desc = "Zhōngwén"
more = "中文"
see = ['zh-Hans', 'zh-Hant']

# Note here! Can't use upper case!
[zh-hans]
name = "zh-Hans"
desc = "Hanzi Simplified"
more = "简体中文"
see = ['zh', 'zh-Hant']

[zh-hant]
name = "zh-Hant"
desc = "Hanzi Traditional"
more = "繁体中文"
see = ['zh', 'zh-Hans']
